name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: Windows10-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: make
      run: gcc srt2csv.cpp
   
